name: Build Kiosk Launcher Release APK

on:
  workflow_dispatch:  # permet de lancer manuellement
  push:               # optionnel, lance le build à chaque commit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode and setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-key.keystore
          ls -la release-key.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build and Sign APK (release)
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: release-key.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: KioskLauncher-Signed-APK
          path: app/build/outputs/apk/release/app-release.apk
