name: Generate Debug Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
          echo "KEYSTORE_BASE64=$(base64 -w 0 debug.keystore)" >> $GITHUB_ENV
      - name: Create GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh secret set DEBUG_KEYSTORE_BASE64 --body "${{ env.KEYSTORE_BASE64 }}"
